spring.application.name=angular_spring

# Conexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/stockcontrol_schema
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuracion del patron del log
logging.pattern.console=[%thread] %-5level %logger{36} - %msg%n 

# Configuracion del nivel del log
logging.level.root=INFO

# Quitar banner Spring
spring.main.banner-mode=off